<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="library" nsURI="http://www.eclipse.org/emf/compare/uml2/library/1.0"
    nsPrefix="librarycompare">
  <eClassifiers xsi:type="ecore:EClass" name="BookTheftDiff" eSuperTypes="../../org.eclipse.emf.compare.uml2/model/uml2compare.ecore#//UMLDiff">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="borrowerName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bookName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
